# https://starship.rs/config/

[character]
success_symbol = '[ğŸŒ±](bold green)'
error_symbol = '[ğŸ‚](bold red)'

[container]
style = 'bold blue dimmed'
format = '($style)'

[custom.container_name]
command = "cname"
when = "cname"
symbol = 'ğŸ«™'
style = 'bold blue dimmed'
format = "[$symbol $output]($style) "
