[character]
success_symbol = "[❯](bold #5e81ac)"
error_symbol = "[✗](#bf616a)"

[directory]
format = "[$path]($style fg:#5e81ac) "
read_only = " "

[cmd_duration]
format = '[ $duration ]($style fg:#4c566a)'

[git_branch]
format = "[on]($style fg:#d08770) [$symbol$branch ]($style fg:#a3be8c)"

[git_status]
style = "bold fg:#d08770"

[python]
style = "bold fg:#d08770"
# Original python status doesn't have space ater it.
# It mixed with the next status. Otherwise, we don't
# need to override the format here.
format = '[${symbol}${pyenv_prefix}(${version}) (\($virtualenv\)) ]($style)'

[rust]
style = "bold fg:#bf616a"

[nodejs]
symbol = "⬢ "
# Can't display the symbol correctly without overriding format
format = '[$symbol($version) ]($style fg:#a3be8c)'