# https://starship.rs/config

command_timeout = 700 # default: 500

[character]
success_symbol = '[ğŸ¦„](bold green)'
error_symbol = '[ğŸ™Š](bold red)'

[container]
style = 'bold blue dimmed'
format = '($style)'

[custom.container_name]
command = "container_name"
when = "container_name"
symbol = 'ğŸ«™'
style = 'bold blue dimmed'
format = "[$symbol $output]($style) "

[shell]
disabled = true
fish_indicator = 'ğŸ¡'
nu_indicator = 'ğŸ¦€'
zsh_indicator = 'ğŸ¦ª'
bash_indicator = 'ğŸš'
unknown_indicator = 'mystery shell'
