# https://starship.rs/config/

command_timeout = 700 # default: 500

[character]
success_symbol = '[ğŸ¦„](bold green)'
error_symbol = '[ğŸ™Š](bold red)'

[container]
style = 'bold blue dimmed'
format = '($style)'

[custom.container_name]
command = "container_name"
when = "container_name"
symbol = 'ğŸ«™'
style = 'bold blue dimmed'
format = "[$symbol $output]($style) "

[shell]
disabled = true
fish_indicator = 'ğŸ¡'
nu_indicator = 'ğŸ¦€'
zsh_indicator = 'ğŸ¦ª'
bash_indicator = 'ğŸš'
unknown_indicator = 'mystery shell'

[custom.jj]
detect_folders = [".jj"]
symbol = "jj:"
command = '''
jj log -r@ -l1 --ignore-working-copy --no-graph --color always  -T '
  separate(" ",
    branches.map(|x| if(
        x.name().substr(0, 10).starts_with(x.name()),
        x.name().substr(0, 10),
        x.name().substr(0, 9) ++ "â€¦")
      ).join(" "),
    tags.map(|x| if(
        x.name().substr(0, 10).starts_with(x.name()),
        x.name().substr(0, 10),
        x.name().substr(0, 9) ++ "â€¦")
      ).join(" "),
    surround("\"","\"",
      if(
         description.first_line().substr(0, 24).starts_with(description.first_line()),
         description.first_line().substr(0, 24),
         description.first_line().substr(0, 23) ++ "â€¦"
      )
    ),
    if(conflict, "conflict"),
    if(divergent, "divergent"),
    if(hidden, "hidden"),
  )
'
'''

[custom.jjstate]
detect_folders = [".jj"]
command = '''
jj log -r@ -l1 --no-graph -T "" --stat | tail -n1 | sd "(\d+) files? changed, (\d+) insertions?\(\+\), (\d+) deletions?\(-\)" " ${1}m ${2}+ ${3}-" | sd " 0." ""
'''
