# https://starship.rs/config/

command_timeout = 700

[character]
# success_symbol = '[ğŸ¦„](bold green)'
# error_symbol = '[ğŸ™Š](bold red)'

[container]
style = 'bold blue dimmed'
format = '($style)'

[custom.container_name]
command = "container_name"
when = "container_name"
symbol = 'ğŸ«™'
style = 'bold blue dimmed'
format = "[$symbol $output]($style) "

[shell]
fish_indicator = 'ğŸ¡'
zsh_indicator = 'ğŸ”'
bash_indicator = 'ğŸš'
nu_indicator = 'ğŸ¦Š'
unknown_indicator = 'mystery shell'

disabled = false
